// Game object implimentation code.
// Auto-generated by Creer, please do not mess with unless you want your
// game data to start breaking
package ${underscore(game_name)}
<%include file='functions.noCreer' />
% for obj_name in game_obj_names:
<%
    obj = game_objs[obj_name]
%>
struct ${obj_name}Impl {
    data map[string]interface{}
}

%   for attr_name in obj['attribute_names']:
<%
        attr = obj['attributes'][attr_name]
        ret_type = shared['go']['type'](attr['type'])
%>func (this ${obj_name}) ${lowercase_first(attr_name)}() ${ret_type} {
    return this.data["${attr_name}"].(${ret_type})
}

%   endfor
%   for func_name in obj['function_names']:
<%
        func = obj['functions'][func_name]
%>
%   endfor
% endfor
